apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: digitalbank
  namespace: argocd
spec:
  description: Digital Banking Platform
  
  sourceRepos:
    - 'https://github.com/your-org/digitalbanking.git'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
  
  destinations:
    - namespace: 'digitalbank-*'
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  
  roles:
    - name: admin
      description: Admin privileges
      policies:
        - p, proj:digitalbank:admin, applications, *, digitalbank/*, allow
      groups:
        - digitalbank-admins
    
    - name: developer
      description: Developer privileges
      policies:
        - p, proj:digitalbank:developer, applications, get, digitalbank/*, allow
        - p, proj:digitalbank:developer, applications, sync, digitalbank/*, allow
      groups:
        - digitalbank-developers
