#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  🚀 Jenkins CI/CD Server - Setup Complete"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📍 Access Jenkins at: http://34.31.22.16/jenkins"
echo ""
echo "🔐 Initial Setup (No Password Required)"
echo "   - Setup wizard is disabled"
echo "   - Default admin user will be created on first login"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Access Jenkins: http://34.31.22.16/jenkins"
echo ""
echo "2. Install Required Plugins:"
echo "   - Go to Manage Jenkins → Plugins"
echo "   - Install: Kubernetes, Docker Pipeline, Git, Pipeline"
echo ""
echo "3. Configure Kubernetes Cloud:"
echo "   kubectl config view --raw > kubeconfig.yaml"
echo "   # Upload this in Jenkins → Manage Jenkins → Clouds → Kubernetes"
echo ""
echo "4. Create Pipeline Job:"
echo "   - New Item → Pipeline"
echo "   - Pipeline → Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: <your-git-repo>"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "5. Configure GCP Credentials:"
echo "   gcloud iam service-accounts keys create jenkins-key.json \\"
echo "     --iam-account=jenkins-sa@charged-thought-485008-q7.iam.gserviceaccount.com"
echo "   # Add as Secret File in Jenkins credentials"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  🔍 Security Scanning Tools Configured:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Checkov - IaC Security Scanner"
echo "   - Scans: Terraform, Kubernetes, Dockerfiles"
echo "   - Pipeline Stage: 'Security Scan - Checkov (IaC)'"
echo ""
echo "✅ Trivy - Container Vulnerability Scanner"
echo "   - Scans: Docker images for CVEs"
echo "   - Pipeline Stage: 'Security Scan - Trivy (Container Images)'"
echo "   - Severity: HIGH, CRITICAL"
echo ""
echo "✅ Kyverno - Kubernetes Policy Engine"
echo "   - Policies Applied:"
echo "     • require-labels: Enforce app/tier labels"
echo "     • require-non-root: Containers run as non-root"
echo "     • disallow-latest-tag: No :latest tags allowed"
echo "     • require-resource-limits: CPU/Memory limits required"
echo "   - Pipeline Stage: 'Security Scan - Kyverno Policies'"
echo ""
echo "Check policies: kubectl get clusterpolicy"
echo "View reports:   kubectl get policyreport -A"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  📊 Pipeline Stages (Jenkinsfile):"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Checkout - Get source code"
echo "2. Security Scan - Checkov (IaC)"
echo "3. Build Images - All microservices (parallel)"
echo "4. Security Scan - Trivy (Container vulnerabilities)"
echo "5. Push to GCR - Push images to Google Container Registry"
echo "6. Deploy to GKE - Deploy to Kubernetes"
echo "7. Security Scan - Kyverno Policies"
echo "8. Verify Deployment - Check all services running"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  🎯 For Project Defense Demo:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Show the Jenkinsfile with all security stages"
echo "2. Run the pipeline (Build Now)"
echo "3. Show Checkov scan results (IaC security)"
echo "4. Show Trivy scan results (Container vulnerabilities)"
echo "5. Show Kyverno policy reports:"
echo "   kubectl get policyreport -A"
echo "   kubectl describe policyreport <name> -n digitalbank-apps"
echo "6. Show ArgoCD GitOps integration"
echo "7. Show Prometheus/Grafana monitoring"
echo "8. Show ELK logging stack"
echo ""
echo "════════════════════════════════════════════════════════════"

# Check Kyverno status
echo ""
echo "📊 Current Kyverno Policy Status:"
kubectl get clusterpolicy
echo ""
echo "📋 Policy Reports:"
kubectl get policyreport -A 2>/dev/null || echo "No policy reports yet (will be generated after deployments)"
echo ""
echo "════════════════════════════════════════════════════════════"
